services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
