FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# força o Vite a escutar em 0.0.0.0 para sair do container
CMD ["npm", "run", "dev", "--", "--host"]
